# Generated by Django 2.2.13 on 2022-04-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bid',
        ),
    ]
