# Generated by Django 2.2.13 on 2022-04-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0002_remove_book_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='B_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
